# Generated by Django 6.1.1 on 2026-09-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='comentarios',
        ),
    ]
