# Generated by Django 6.1.1 on 2026-09-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_estudiante_cedula'),
        ('registro', '0002_remove_estudiante_comentarios'),
    ]

    operations = [
    ]
