# Generated by Django 6.1.1 on 2026-09-27 18:34

import django.core.validators
import django.db.models.functions.text
import registro.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_merge_20260926_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ('-fecha_registro',), 'verbose_name': 'estudiante', 'verbose_name_plural': 'estudiantes'},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Use únicamente letras, espacios, apóstrofes o guiones.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ' -]+$")]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(choices=[('SOF', 'Software'), ('ADM', 'Administración'), ('DER', 'Derecho'), ('OTR', 'Otra')], max_length=3),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[registro.validators.validar_cedula_ecuatoriana], verbose_name='cédula'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Use únicamente letras, espacios, apóstrofes o guiones.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ' -]+$")]),
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.CheckConstraint(condition=models.Q(('edad__gte', 16), ('edad__lte', 100)), name='estudiante_edad_entre_16_y_100'),
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('correo'), name='estudiante_correo_unico_sin_mayusculas'),
        ),
    ]
